---
title: "Project"
output: html_document
date: "2023-05-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("sva")
#install.packages('SVA')
library(limma)
library(sva)
```


```{r}
data1 <- read.delim('dataset1.txt', row.names = 1)
data2 <- read.delim('dataset2.txt',row.names =1)
data3 <- read.delim('dataset3.txt', sep = ' ')
```

```{r}
# Match row names using gene symbol
common_genes <- intersect(row.names(data1), intersect(row.names(data2),row.names(data3)))
data1_matched <- data1[common_genes, ]
data2_matched <- data2[common_genes, ]
data3_matched<- data3[common_genes, ]
```

```{r}

# Create a batch variable based on the dataset
batch <- factor(rep(1:3, c(ncol(data1), ncol(data2), ncol(data3))))
```

```{r}
#batch correct the data
combined_data <- cbind(data1_matched, data2_matched, data3_matched)
comb <- combined_data

combined_data_normalized <- ComBat(combined_data, batch=batch)
```
```{r}
#Before differ. exp anal, need to make vector of conditions (0 is control)

#data 2 15B - 0, 16B - 0, 17B - 1, 18B - 1, 19B - 1, 1A - 1, 1B - 1, 20B -1
# 21B -1,22B -1,23B -0,24B-0,25B-0,2A-1,2B-1,3A-1,3B-1,4A-1,5A-1,5B-1,6A-1,6B-1,7B-0.8B-0
cond2 <- c('HC','HC','CD','CD','CD','CD','CD','CD','CD','CD','HC','HC','HC','CD','CD','CD','CD','CD','CD','CD','CD','CD','HC','HC')
cond1 <- c()
cond3 -c()
condition <- c(cond1,cond2,cond3)
```



```{r}
# Perform differential expression analysis with LIMMA
design <- model.matrix(~0 + condition) # use condition as the only variable in the model
colnames(design) <- levels(condition)
fit <- lmFit(combined_data_normalized, design)
fit <- eBayes(fit)
results <- topTable(fit, coef=1, n=Inf) # compare treatment vs control
```

