---
title: "Clustering-146-Project"
output: pdf_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(cluster)
library(factoextra)
```

```{r}
data = read.csv('~/Desktop/Education/Spring Term/QBS-146/combined_data_1_2_normalized.csv')
colnames(data)[-1] = unlist(lapply(colnames(data)[-1],substring,first=2))
head(data)
```


```{r}
labels = read.csv("~/Desktop/Education/Spring Term/QBS-146/labels_1_2.csv")
```

```{r}
data_vals = data[,2:ncol(data)]
#normalized_df = apply(data_vals, 2, function(x) (x - min(x)) / (max(x) - min(x)))

data_vals = t(data_vals)

normalized_df = scale(data_vals)

pca_data = prcomp(normalized_df, center = TRUE, scale = TRUE)

summary(pca_data)
```
```{r}
hist(data_vals)
```


```{r}
library(ggplot2)
eigenvalues = pca_data$sdev^2

# Calculate the proportion of variance explained by each principal component
variance_explained = eigenvalues / sum(eigenvalues)

# Create a scree plot
scree_plot = ggplot(data = data.frame(PC = 1:length(variance_explained), VarianceExplained = variance_explained),
                     aes(x = PC, y = VarianceExplained)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(x = "Principal Component", y = "Proportion of Variance Explained") +
  ggtitle("Scree Plot")

# Display the scree plot
print(scree_plot)
```



```{r}
num_components = sum(cumsum(variance_explained) <= 0.90) + 1

# Extract the relevant components from the PCA result
selected_components = pca_data$x[, 1:num_components]

# Create a dataframe with the selected components
df_selected_components = as.data.frame(selected_components)

# Print the resulting dataframe
print(df_selected_components)
```
## KMeans on dataset itself

```{r}
k = 3

# Perform k-means clustering on the selected components
kmeans_result = kmeans(normalized_df, centers = k)

# Retrieve the cluster assignments
cluster_assignments = kmeans_result$cluster
```

```{r}
silhouette_scores = silhouette(kmeans_result$cluster, dist(normalized_df))

# Calculate the average silhouette score
average_silhouette_score = mean(silhouette_scores[, "sil_width"])
average_silhouette_score
```

```{r}
#calculate gap statistic based on number of clusters
gap_stat <- clusGap(normalized_df,
                    FUN = pam,
                    K.max = 10, #max clusters to consider
                    B = 50) #total bootstrapped iterations

#plot number of clusters vs. gap statistic
fviz_gap_stat(gap_stat)

# Extract the gap statistic values
gap_values <- gap_stat$Tab[, "gap"]

# Find the optimal k value
optimal_k <- max(which(diff(gap_values) >= 0))
```

```{r}
library(cluster)
library(factoextra)
library(ggplot2)
library(ggrepel)

# Perform k-medoids clustering
clust <- pam(normalized_df, k=3)  # Replace 'normalized_df' with your data and 'k' with the desired number of clusters

# Merge class labels with clustering results
merged_df <- data.frame(ID = rownames(normalized_df), Cluster = clust$clustering)
merged_df$ClassLabel <- labels$x[match(merged_df$ID, rownames(labels))]

# Visualize clustering results with actual class labels
p <- fviz_cluster(clust, data = normalized_df, geom = "point", frame = FALSE) +
  geom_text(aes(label = labels$x), nudge_x = 0.2, nudge_y = 0.2)

# Display the plot
print(p)
```
```{r}
# Calculate silhouette scores
scores = clust$silinfo
silhoute_score = scores$widths[,"sil_width"]
mean(silhoute_score)
```


```{r}
# Visualize clustering results with actual class labels
p <- fviz_cluster(kmeans_result, data = normalized_df, geom = "point", frame = FALSE) +
  geom_text(aes(label = labels$x), nudge_x = 0.2, nudge_y = 0.2)

# Display the plot
print(p)
```
```{r}
#calculate gap statistic based on number of clusters
gap_stat <- clusGap(normalized_df,
                    FUN = kmeans,
                    K.max = 10, #max clusters to consider
                    B = 50) #total bootstrapped iterations

#plot number of clusters vs. gap statistic
fviz_gap_stat(gap_stat)
```
## Rand Index
```{r}
#KMeans
library(fossil)

clust1 = as.numeric(kmeans_result$cluster)
clust2 = as.numeric(factor(labels$x))
rand_index <- rand.index(clust1,clust2)
rand_index
```

```{r}
clust1 = as.numeric(clust$clustering)
clust2 = as.numeric(factor(labels$x))
rand_index <- rand.index(clust1,clust2)
rand_index
```




